---
- name: instalando uma lista de pacotes
  hosts: all
  tasks:
    - name: instalando pacotes
      become: true
      apt:
        name "{{ item }}"
      loop:
        - sl
        - git
        - vim
        - ncdu
        - jq
      when: ansible_distribution == "Debian"
