- name: Instalando uma lista de pacotes para maquina centos
  hosts: centos
  vars:
    - packages:
        - wget
        - vim
        - tree
  tasks:
    - name: Instalando pacotes
      become: true
      yum:
        name: "{{ packages }}"
