---
- name: variable plabook test
  hosts: localhost
    
  tasks:
  - name: Ensure httpd package is present
    yum:
      name: httpd
      state: latest
    register: httpd_results

  - name: Restart httpd
    service:
      name: httpd
      state: restart
    when: httpd_results.changed
