---
- name: variable playbook test
  hosts: localhost
  gather_facts: true

  vars:
    var_one: awesome
    var_two: ansible is
    var_three: "{{ var_two }} {{ var_one }}"

  tasks:
    - name:
      debug:
        msg: "{{ var_three }}"
