---
- name: variable playbook test
  hosts: localhost
  become: yes
  tasks:
  - name: Install apache
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == 'Debian' or
          ansible_distribution == 'Ubuntu'

  - name: Install httpd
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == 'Redhat'

  - name: Install nginx
    pacman:
      name: nginx
      state: latest
    when: ansible_distribution == 'Archlinux'
